version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: Git restore cache
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - run: 
          name: Fetch git tags 
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects 
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  bundle_install:
    description: "Bundle install"
    steps:
      - restore_cache:
          name: Bundle modules cache restore
          keys:
            - bundle-v1-{{ checksum "Gemfile" }}
            - bundle-v1-
      - run:
          name: Bundle install
          command: |
            bundle install --path ./modules
      - save_cache:
          name: Bundle modules cache save
          key: bundle-v1-{{ checksum "Gemfile" }}
          paths:
            - "modules"
  build:
    description: "Build Jekyll site"
    steps:
      - restore_cache:
          name: "Build cache restore"
          keys:
            - _site-v1-{{ .Revision }}
            - _site-v1-
      - run:
          name: Building Jekyll site
          command: bundle exec jekyll build --incremental
      - save_cache:
          name: Build cache save
          key: _site-v1-{{ .Revision }}
          paths:
            - _site
  deploy:
    description: "Deploy to static branches"
    parameters:
      target_branch:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: www
      - run:
          name: Tag build
          command: echo "<< parameters.target_branch >> $(date)" > www/version
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages@2.0.1
            git config user.email "ci-config@gmail.com"
            git config user.name "ci-config"
      - add_ssh_keys:
          fingerprints:
            - "e0:2e:c5:c2:f0:93:95:6d:01:32:62:0a:d1:6e:82:c1	"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages -d www --branch << parameters.target_branch >>
  docker_build_push:
    description: "Build and Push image to docker hub"
    steps:
      - setup_remote_docker
      - run:
          name: Building docker image for production
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/binary-static-academy:${CIRCLE_SHA1} -t ${DOCKHUB_ORGANISATION}/binary-static-academy:latest .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/binary-static-academy:${CIRCLE_SHA1}
            docker push ${DOCKHUB_ORGANISATION}/binary-static-academy:latest
  k8s_deploy:
    description: "Deploy to k8s cluster"
    steps:
      - k8s/install-kubectl
      - run: 
          name: Deploying to k8s cluster for service binary-academy
          command: |
            for SERVER_ID in {1..5}
            do
              KUBE_SERVER_REF="KUBE_SERVER_$SERVER_ID"
              SERVICEACCOUNT_TOKEN_REF="SERVICEACCOUNT_TOKEN_$SERVER_ID"
              CA_CRT_REF="CA_CRT_$SERVER_ID"
              if [ ! -z "${!KUBE_SERVER_REF}" ]
              then
                echo "Deploying to cluster $SERVER_ID"
                CA_CRT="${!CA_CRT_REF}"
                KUBE_SERVER="${!KUBE_SERVER_REF}"
                SERVICEACCOUNT_TOKEN="${!SERVICEACCOUNT_TOKEN_REF}"
                echo $CA_CRT | base64 --decode > ca.crt
                kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/academy-binary-com academy-binary-com=${DOCKHUB_ORGANISATION}/binary-static-academy:${CIRCLE_SHA1}
              fi
            done

jobs:
  release_production:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - git_checkout_from_cache
      - bundle_install
      - build
      - deploy
        - target_branch: "production"
  release_aws_production:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - git_checkout_from_cache
      - bundle_install
      - build
      - docker_build_push
      - k8s_deploy
      
workflows:
  release:
    jobs:
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
      - release_aws_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^aws\-production.*/
          context: binary-frontend-artifact-upload
